apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prompts
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:P7-Chaos-Academy/gitops.git
    targetRevision: main
    path: pi/prompts
  destination:
    server: https://kubernetes.default.svc
    namespace: prompts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true