apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-backend-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:P7-Chaos-Academy/gitops.git
    targetRevision: main
    path: pi/cluster-api
  destination:
    server: https://kubernetes.default.svc
    namespace: backend-deployment # The namespace to deploy to
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30081
      protocol: TCP