apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-annotator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:P7-Chaos-Academy/gitops.git
    targetRevision: main
    path: pi/node-annotator
  destination:
    server: https://kubernetes.default.svc
    namespace: nodeannotations
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true