---
apiVersion: v1
kind: Namespace
metadata:
  name: cluster-api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-api-node-annotator
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-api-node-annotator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-api-node-annotator
subjects:
- kind: ServiceAccount
  name: default
  namespace: cluster-api
- kind: ServiceAccount
  name: default
  namespace: cluster-namespace
