apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: strato-api-hpa
  namespace: strato-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: strato-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
